/** Minimal valid AppData seed for a new workspace (server-side). */
export const EMPTY_WORKSPACE_DATA = {
  requests: [],
  sources: [],
  reports: [],
  blockers: [],
  handoffs: [],
  ideas: [],
  brainUpdates: [],
  training: [],
  announcements: [],
  admin: { unlocked: false, passcode: "landon-admin" },
  rewardState: {
    level: "Research Trainee",
    points: 0,
    badges: [],
    recentAchievements: [],
    suggestedNextSkill: "How to use AI responsibly",
  },
  settings: {
    appName: "LandonOS Research Command Center",
    userName: "Landon",
    userRole: "Research Lead",
    roleLabels: ["Landon", "Rose", "Carmen", "Gregg", "Leadership"],
    researchTypes: [
      "Compliance",
      "Business",
      "Market",
      "Competitor",
      "Client-Account",
      "Internal Operations",
    ],
    sourceTypes: [
      "Official Source",
      "Internal Company Record",
      "Client-Provided",
      "Competitor",
      "Market-Industry",
      "AI Draft",
      "Unknown",
    ],
    rewardSettings: {
      completeResearch: 200,
      addOfficialSource: 50,
      improvePrompt: 25,
      raiseBlockerEarly: 40,
      completeReport: 150,
      completeHandoff: 120,
      reportApproved: 250,
      suggestBrainUpdate: 60,
      completeLesson: 75,
    },
  },
};
