import { AppData } from "./types";

export const RESEARCH_TYPES = [
  "Compliance",
  "Business",
  "Market",
  "Competitor",
  "Client-Account",
  "Internal Operations",
];

export const SOURCE_TYPES = [
  "Official Source",
  "Internal Company Record",
  "Client-Provided",
  "Competitor",
  "Market-Industry",
  "AI Draft",
  "Unknown",
];

export const GPS_STEPS = [
  "Understand request",
  "Build research questions",
  "Find sources",
  "Verify sources",
  "Compare findings",
  "Identify risks and opportunities",
  "Build report",
  "Quality check",
  "Handoff",
  "Company Brain update suggestion",
];

export const defaultData: AppData = {
  requests: [
    {
      id: "req-1",
      title: "Q3 Vendor Compliance Audit",
      type: "Compliance",
      requester: "Carmen",
      reviewer: "Rose",
      priority: "High",
      dueDate: "2026-06-20",
      whatTryingToFindOut: "Are our primary cloud vendors still SOC 2 compliant?",
      decisionSupported: "Contract renewals for Q4.",
      whatWeKnow: "Last check was done in 2025. AWS and Azure were compliant.",
      requiredSources: "Official SOC 2 reports from vendor trust centers.",
      whatNotToAssume: "Do not assume past compliance implies current compliance.",
      completionCriteria: "A clear list of vendors with current compliance status and links to reports.",
      requiresHumanReview: true,
      notes: "Need to finish this before the executive meeting.",
      status: "In Progress",
      gpsSteps: {
        "Understand request": "Complete",
        "Build research questions": "Complete",
        "Find sources": "In Progress",
        "Verify sources": "Not Started",
        "Compare findings": "Not Started",
        "Identify risks and opportunities": "Not Started",
        "Build report": "Not Started",
        "Quality check": "Not Started",
        "Handoff": "Not Started",
        "Company Brain update suggestion": "Not Started",
      },
    },
    {
      id: "req-2",
      title: "Data Residency Requirements - EU Expansion",
      type: "Compliance",
      requester: "Gregg",
      reviewer: "Carmen",
      priority: "Executive",
      dueDate: "2026-06-25",
      whatTryingToFindOut: "What data residency rules apply if we onboard EU clients?",
      decisionSupported: "Go / no-go on the EU expansion plan.",
      whatWeKnow: "GDPR applies. We currently host all data in US-East.",
      requiredSources: "Official GDPR guidance, regulator publications, legal summaries.",
      whatNotToAssume: "Do not assume US hosting is acceptable for EU personal data.",
      completionCriteria: "A summary of residency obligations and hosting options with cost impact.",
      requiresHumanReview: true,
      notes: "Gregg wants this for the board prep.",
      status: "Open",
      gpsSteps: {
        "Understand request": "Complete",
        "Build research questions": "In Progress",
        "Find sources": "Not Started",
        "Verify sources": "Not Started",
        "Compare findings": "Not Started",
        "Identify risks and opportunities": "Not Started",
        "Build report": "Not Started",
        "Quality check": "Not Started",
        "Handoff": "Not Started",
        "Company Brain update suggestion": "Not Started",
      },
    },
    {
      id: "req-3",
      title: "Competitor Pricing - Mid-Market Tier",
      type: "Competitor",
      requester: "Rose",
      reviewer: "Gregg",
      priority: "Medium",
      dueDate: "2026-07-02",
      whatTryingToFindOut: "How are our top 3 competitors pricing their mid-market plans?",
      decisionSupported: "Repricing our Growth plan.",
      whatWeKnow: "Two competitors publish pricing publicly; one is quote-only.",
      requiredSources: "Public pricing pages, analyst notes, customer reviews.",
      whatNotToAssume: "Do not assume listed prices reflect actual discounts.",
      completionCriteria: "A comparison table of plans, prices, and key limits.",
      requiresHumanReview: false,
      notes: "",
      status: "In Progress",
      gpsSteps: {
        "Understand request": "Complete",
        "Build research questions": "Complete",
        "Find sources": "Complete",
        "Verify sources": "In Progress",
        "Compare findings": "Not Started",
        "Identify risks and opportunities": "Not Started",
        "Build report": "Not Started",
        "Quality check": "Not Started",
        "Handoff": "Not Started",
        "Company Brain update suggestion": "Not Started",
      },
    },
  ],
  sources: [
    {
      id: "src-1",
      title: "AWS Artifact - SOC 2 Type II",
      urlOrFileRef: "https://aws.amazon.com/artifact/",
      type: "Official Source",
      relatedResearchId: "req-1",
      dateCaptured: "2026-06-12",
      summary: "Current SOC 2 report for AWS showing full compliance.",
      keyFacts: "- SOC 2 Type II valid through 2026\n- No major exceptions noted",
      confidenceRating: 10,
      sourceQualityRating: 10,
      tags: ["AWS", "SOC2", "Compliance"],
      notes: "Downloaded the PDF and stored in the secure vault.",
    },
    {
      id: "src-2",
      title: "Azure Trust Center Compliance Listing",
      urlOrFileRef: "https://www.microsoft.com/trust-center",
      type: "Official Source",
      relatedResearchId: "req-1",
      dateCaptured: "2026-06-12",
      summary: "Microsoft Azure compliance offerings including SOC 2 and ISO 27001.",
      keyFacts: "- SOC 2 Type II current\n- ISO 27001 certified",
      confidenceRating: 9,
      sourceQualityRating: 10,
      tags: ["Azure", "SOC2", "ISO27001"],
      notes: "",
    },
    {
      id: "src-3",
      title: "GDPR Data Transfer Summary (AI Draft)",
      urlOrFileRef: "internal note",
      type: "AI Draft",
      relatedResearchId: "req-2",
      dateCaptured: "2026-06-13",
      summary: "AI-generated overview of GDPR data transfer mechanisms.",
      keyFacts: "- Mentions SCCs and adequacy decisions\n- Needs verification against official text",
      confidenceRating: 4,
      sourceQualityRating: 3,
      tags: ["GDPR", "EU", "Draft"],
      notes: "Must verify against official EU Commission guidance before use.",
    },
    {
      id: "src-4",
      title: "Competitor A Public Pricing Page",
      urlOrFileRef: "https://competitor-a.example.com/pricing",
      type: "Competitor",
      relatedResearchId: "req-3",
      dateCaptured: "2026-06-11",
      summary: "Published pricing for Competitor A across all tiers.",
      keyFacts: "- Growth tier $79/user/mo\n- Annual discount ~20%",
      confidenceRating: 7,
      sourceQualityRating: 6,
      tags: ["Pricing", "Competitor"],
      notes: "Prices may not reflect negotiated enterprise discounts.",
    },
    {
      id: "src-5",
      title: "Unverified Forum Thread on Vendor Outage",
      urlOrFileRef: "https://forum.example.com/thread/123",
      type: "Unknown",
      relatedResearchId: "req-1",
      dateCaptured: "2026-06-10",
      summary: "Forum users discussing a possible vendor outage and compliance lapse.",
      keyFacts: "- Anecdotal claims only\n- No official confirmation",
      confidenceRating: 2,
      sourceQualityRating: 2,
      tags: ["Forum", "Unverified"],
      notes: "Treat as a lead only. Do not cite in a report.",
    },
  ],
  reports: [
    {
      id: "rep-1",
      title: "Vendor Compliance Status - Draft",
      relatedResearchId: "req-1",
      preparedFor: "Leadership",
      preparedBy: "Landon",
      date: "2026-06-13",
      objective: "Confirm current SOC 2 status of primary cloud vendors ahead of Q4 renewals.",
      executiveSummary:
        "AWS and Azure both maintain current SOC 2 Type II compliance. No blocking issues identified for renewal.",
      keyFindings:
        "- AWS SOC 2 Type II valid through 2026\n- Azure SOC 2 Type II current, also ISO 27001 certified",
      sourceBackedFacts:
        "Both findings confirmed via official vendor trust centers (AWS Artifact, Azure Trust Center).",
      risks: "A forum thread alleges a vendor outage; unverified and excluded from conclusions.",
      opportunities: "Consolidating to two compliant vendors simplifies our audit posture.",
      unknowns: "Renewal pricing impact not yet confirmed.",
      recommendation: "Proceed with renewals pending finance review of pricing.",
      nextSteps: "Attach finalized vendor list to renewal package; route to Rose for review.",
      sourcesReviewed: ["src-1", "src-2"],
      reviewerNotes: "Rose: please confirm whether the forum claim warrants a follow-up.",
      status: "Ready for Review",
    },
  ],
  blockers: [
    {
      id: "blk-1",
      relatedResearchId: "req-2",
      type: "I found conflicting information",
      description:
        "Different summaries disagree on whether SCCs alone are sufficient for US hosting of EU data.",
      urgency: "High",
      whoShouldHelp: "Carmen",
      whatTried: "Compared two AI summaries and one blog post; still unclear.",
      suggestedNextStep: "Locate the official EU Commission guidance and a legal summary.",
      status: "Open",
    },
    {
      id: "blk-2",
      relatedResearchId: "req-3",
      type: "I can't find sources",
      description: "Competitor C is quote-only; no public pricing available.",
      urgency: "Medium",
      whoShouldHelp: "Rose",
      whatTried: "Checked their site, G2, and Capterra.",
      suggestedNextStep: "Ask sales if we have any competitive intel on Competitor C.",
      status: "In Review",
    },
  ],
  handoffs: [
    {
      id: "hnd-1",
      title: "Competitor Pricing - Preliminary Findings",
      whatResearched: "Public pricing for mid-market plans across top competitors.",
      whyItMatters: "Informs repricing of our Growth plan.",
      whatFound: "Competitor A at $79/user/mo with ~20% annual discount; Competitor B comparable.",
      stillUnknown: "Competitor C pricing (quote-only).",
      recommendedAction: "Consider positioning Growth between A and B; revisit after C intel.",
      whoReviews: "Gregg",
      affectsCompanyDecision: true,
      affectsClientFacing: false,
      updateCompanyBrain: true,
      sourcesAttached: ["src-4"],
      reportAttached: "",
      status: "Ready for Gregg",
    },
  ],
  ideas: [
    {
      id: "idea-1",
      title: "Automate vendor compliance re-checks",
      category: "Automation",
      description: "Set a quarterly reminder workflow to re-verify vendor SOC 2 status.",
      whyItMatters: "Prevents relying on stale compliance data at renewal time.",
      suggestedNextAction: "Draft a simple checklist and calendar cadence.",
      convertTo: "Automation Idea",
    },
    {
      id: "idea-2",
      title: "Build a reusable EU data residency brief template",
      category: "Compliance Support",
      description: "A standard outline for residency questions to speed up future research.",
      whyItMatters: "We will keep getting EU expansion questions.",
      suggestedNextAction: "Capture the outline once req-2 is complete.",
      convertTo: "Company Brain Update Suggestion",
    },
  ],
  brainUpdates: [
    {
      id: "brn-1",
      title: "Record approved vendor list for Q4",
      relatedResearchId: "req-1",
      recommendedRecord: "Decision Log",
      whatChanged: "Confirmed AWS and Azure as compliant for Q4 renewals.",
      whyItMatters: "Creates an auditable record of the renewal decision basis.",
      draftUpdateText:
        "Q4 vendor renewals: AWS and Azure confirmed SOC 2 compliant via official trust centers on 2026-06-12.",
      status: "Suggested",
    },
  ],
  training: [
    {
      id: "trk-1",
      title: "How to use AI responsibly",
      lessons: [
        {
          id: "les-1-1",
          title: "AI output is a draft, not a fact",
          explanation:
            "AI can draft and summarize, but every claim must be checked against a real, citable source before it informs a decision.",
          checklist: [
            { text: "Label AI output as a draft", done: true },
            { text: "Identify each claim that needs a source", done: false },
            { text: "Replace assumptions with verified facts", done: false },
          ],
          completed: false,
          practiceTask: "Take one AI summary and mark every claim that still needs a source.",
          relatedModule: "AI Prompt Coach",
        },
        {
          id: "les-1-2",
          title: "Writing prompts that ask for sources",
          explanation:
            "A good research prompt explicitly asks for official sources and flags uncertainty instead of inventing answers.",
          checklist: [
            { text: "Ask for official sources in the prompt", done: false },
            { text: "Ask the model to flag what it is unsure about", done: false },
          ],
          completed: false,
          practiceTask: "Rewrite a rough prompt so it requires official sources.",
          relatedModule: "AI Prompt Coach",
        },
      ],
    },
    {
      id: "trk-2",
      title: "How to verify sources",
      lessons: [
        {
          id: "les-2-1",
          title: "Official vs. unknown sources",
          explanation:
            "Prefer official sources (regulators, vendor trust centers, primary records). Flag AI Draft and Unknown sources and never rely on them alone.",
          checklist: [
            { text: "Identify the source type", done: true },
            { text: "Rate source quality and confidence", done: false },
            { text: "Flag AI Draft and Unknown sources", done: false },
          ],
          completed: true,
          practiceTask: "Classify three sources in the Source Vault by type and quality.",
          relatedModule: "Source Vault",
        },
      ],
    },
    {
      id: "trk-3",
      title: "How to write an executive summary",
      lessons: [
        {
          id: "les-3-1",
          title: "Lead with the decision",
          explanation:
            "An executive summary states the recommendation first, then the few facts that support it. Keep it short and source-backed.",
          checklist: [
            { text: "State the recommendation up front", done: false },
            { text: "Support it with 2-3 source-backed facts", done: false },
          ],
          completed: false,
          practiceTask: "Write a 3-sentence executive summary for an existing report.",
          relatedModule: "Report Builder",
        },
      ],
    },
    {
      id: "trk-4",
      title: "How to research compliance topics",
      lessons: [
        {
          id: "les-4-1",
          title: "Start from the official text",
          explanation:
            "For compliance, begin with the regulation or standard itself, then use summaries only to navigate.",
          checklist: [
            { text: "Find the primary regulation or standard", done: false },
            { text: "Note the exact obligation in scope", done: false },
          ],
          completed: false,
          practiceTask: "Locate the official source for one compliance claim.",
          relatedModule: "Source Vault",
        },
      ],
    },
    {
      id: "trk-5",
      title: "How to research business opportunities",
      lessons: [
        {
          id: "les-5-1",
          title: "Tie findings to a decision",
          explanation:
            "Business research should always connect back to a decision someone has to make.",
          checklist: [
            { text: "Name the decision the research supports", done: false },
            { text: "Collect comparable data points", done: false },
          ],
          completed: false,
          practiceTask: "Write the decision statement for an open business request.",
          relatedModule: "Guided Research Builder",
        },
      ],
    },
    {
      id: "trk-6",
      title: "How to identify risks",
      lessons: [
        {
          id: "les-6-1",
          title: "Separate risk from opportunity",
          explanation:
            "List what could go wrong and what could go right as distinct items, each with evidence.",
          checklist: [
            { text: "List concrete risks", done: false },
            { text: "List concrete opportunities", done: false },
          ],
          completed: false,
          practiceTask: "Add one risk and one opportunity to a draft report.",
          relatedModule: "Report Builder",
        },
      ],
    },
    {
      id: "trk-7",
      title: "How to ask for help early",
      lessons: [
        {
          id: "les-7-1",
          title: "Raise blockers before they cost time",
          explanation:
            "Asking for help early is rewarded. Describe what you tried and what you need.",
          checklist: [
            { text: "Describe the blocker clearly", done: false },
            { text: "Say what you already tried", done: false },
            { text: "Name who can help", done: false },
          ],
          completed: false,
          practiceTask: "Create a blocker that includes what you tried.",
          relatedModule: "Blocked / Need Help",
        },
      ],
    },
    {
      id: "trk-8",
      title: "How to prepare a clean handoff",
      lessons: [
        {
          id: "les-8-1",
          title: "Make the handoff self-contained",
          explanation:
            "A reviewer should understand what you found, why it matters, and what is still unknown without asking you.",
          checklist: [
            { text: "Summarize what was found", done: false },
            { text: "State what is still unknown", done: false },
            { text: "Attach sources and report", done: false },
          ],
          completed: false,
          practiceTask: "Draft a handoff and preview it before routing.",
          relatedModule: "Research Completed Handoff",
        },
      ],
    },
    {
      id: "trk-9",
      title: "How to separate facts from assumptions",
      lessons: [
        {
          id: "les-9-1",
          title: "Label every statement",
          explanation:
            "Mark each statement as a verified fact, an assumption, or an unknown. Only facts belong in conclusions.",
          checklist: [
            { text: "Tag statements as fact / assumption / unknown", done: false },
            { text: "Move assumptions out of the conclusion", done: false },
          ],
          completed: false,
          practiceTask: "Review a report and reclassify one assumption.",
          relatedModule: "Report Builder",
        },
      ],
    },
    {
      id: "trk-10",
      title: "How to suggest Company Brain updates",
      lessons: [
        {
          id: "les-10-1",
          title: "Suggest, never auto-record",
          explanation:
            "Company Brain updates stay suggested until a human reviews them. Provide a clean draft and the reason it matters.",
          checklist: [
            { text: "Pick the right record type", done: false },
            { text: "Write a clear draft update", done: false },
            { text: "Leave status as Suggested", done: false },
          ],
          completed: false,
          practiceTask: "Draft one Company Brain update suggestion.",
          relatedModule: "Company Brain Updates",
        },
      ],
    },
  ],
  announcements: [
    {
      id: "ann-1",
      title: "Mandatory: human review sign-off on every AI-drafted brief",
      body:
        "Effective immediately, no brief that contains AI-drafted content may be routed for a company decision until a named reviewer has signed off. Mark AI Draft sources clearly and attach at least one official source before handoff. This is a compliance requirement, not a guideline.",
      category: "Compliance",
      level: "Critical",
      author: "Carmen (Compliance Lead)",
      date: "2026-06-18",
      pinned: true,
      active: true,
    },
    {
      id: "ann-2",
      title: "Q3 research priorities are locked — EU expansion is the focus",
      body:
        "Leadership has set the EU expansion readiness review as the top research priority for Q3. Data residency, vendor compliance, and competitor pricing in the mid-market tier are the three lanes. Align new requests to one of these where possible.",
      category: "Company",
      level: "Important",
      author: "Gregg (Executive Sponsor)",
      date: "2026-06-15",
      pinned: false,
      active: true,
    },
    {
      id: "ann-3",
      title: "Shout-out: five official-source verifications cleared this week",
      body:
        "Nice work clearing five official-source verifications in the Source Garage this week and raising a blocker early instead of guessing. That is exactly the responsible-research habit we are building. Keep it up.",
      category: "Recognition",
      level: "Info",
      author: "Rose (Team Lead)",
      date: "2026-06-20",
      pinned: false,
      active: true,
    },
  ],
  admin: {
    unlocked: false,
    passcode: "landon-admin",
  },
  rewardState: {
    level: "Source Finder",
    points: 1250,
    badges: ["First Request", "Source Detective", "Early Help Seeker"],
    recentAchievements: [
      "Completed 'How to verify sources' lesson",
      "Added 5 official sources",
      "Raised a blocker early",
    ],
    suggestedNextSkill: "How to write an executive summary",
  },
  settings: {
    appName: "LandonOS Research Command Center",
    userName: "Landon",
    userRole: "Research Lead",
    roleLabels: ["Landon", "Rose", "Carmen", "Gregg", "Leadership"],
    researchTypes: [...RESEARCH_TYPES],
    sourceTypes: [...SOURCE_TYPES],
    rewardSettings: {
      completeResearch: 200,
      addOfficialSource: 50,
      improvePrompt: 25,
      raiseBlockerEarly: 40,
      completeReport: 150,
      completeHandoff: 120,
      reportApproved: 250,
      suggestBrainUpdate: 60,
      completeLesson: 75,
    },
  },
};
